/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poli_bike;

import java.awt.Dimension;

/**
 *
 * @author Propietario
 */
public class Creditos extends javax.swing.JFrame {

    /**
     * Creates new form Creditos
     */
    public Creditos() {
        initComponents();
     //   this.setSize(new Dimension(939, 634));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agradecimientos = new javax.swing.JLabel();
        Agradecimientos1 = new javax.swing.JLabel();
        Agradecimientos2 = new javax.swing.JLabel();
        Agradecimientos3 = new javax.swing.JLabel();
        Agradecimientos4 = new javax.swing.JLabel();
        Grupo = new javax.swing.JLabel();
        Grupo1 = new javax.swing.JLabel();
        Creditos = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        Wallpaper_elefante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agradecimientos.setFont(new java.awt.Font("Brisk", 1, 18)); // NOI18N
        Agradecimientos.setText("Desarrolladores:");
        getContentPane().add(Agradecimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 210, 30));

        Agradecimientos1.setFont(new java.awt.Font("Brisk", 1, 14)); // NOI18N
        Agradecimientos1.setText("López Santamaría Sergio Adrián");
        getContentPane().add(Agradecimientos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 240, 30));

        Agradecimientos2.setFont(new java.awt.Font("Brisk", 1, 14)); // NOI18N
        Agradecimientos2.setText("Programación Avanzada");
        getContentPane().add(Agradecimientos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 240, 30));

        Agradecimientos3.setFont(new java.awt.Font("Brisk", 1, 14)); // NOI18N
        Agradecimientos3.setText("3MV3");
        getContentPane().add(Agradecimientos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 240, 30));

        Agradecimientos4.setFont(new java.awt.Font("Brisk", 1, 14)); // NOI18N
        Agradecimientos4.setText("Arreguin Correa Samantha");
        getContentPane().add(Agradecimientos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 240, 30));

        Grupo.setFont(new java.awt.Font("Brisk", 1, 18)); // NOI18N
        Grupo.setText("Grupo:");
        getContentPane().add(Grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 210, 30));

        Grupo1.setFont(new java.awt.Font("Brisk", 1, 18)); // NOI18N
        Grupo1.setText("Asignatura");
        getContentPane().add(Grupo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 210, 30));

        Creditos.setFont(new java.awt.Font("FrizQuaItcTEE", 0, 36)); // NOI18N
        Creditos.setText("Creditos");
        getContentPane().add(Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jToggleButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(51, 0, 204));
        jToggleButton1.setText("x");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        Wallpaper_elefante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/elefante.jpg"))); // NOI18N
        getContentPane().add(Wallpaper_elefante, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked

        this.setVisible (false);



// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creditos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agradecimientos;
    private javax.swing.JLabel Agradecimientos1;
    private javax.swing.JLabel Agradecimientos2;
    private javax.swing.JLabel Agradecimientos3;
    private javax.swing.JLabel Agradecimientos4;
    private javax.swing.JLabel Creditos;
    private javax.swing.JLabel Grupo;
    private javax.swing.JLabel Grupo1;
    private javax.swing.JLabel Wallpaper_elefante;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
