
package poli_bike;

import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;
import AppPackage.AnimationClass;
import java.awt.Dimension;


public class GUI extends javax.swing.JFrame {
    
  

 //   PanamaHitek_Arduino arduino = new PanamaHitek_Arduino();
 //   SerialPortEventListener escucha; 
                                                                  //en el Monitor Serial
    public GUI() {
      /*  this.escucha = new SerialPortEventListener() {
            
            @Override
            public void serialEvent(SerialPortEvent spe) {
                try {
                    if (arduino.isMessageAvailable())
                    {
                       String mensaje;
                       mensaje = arduino.printMessage(); //
                        usuario.setText(mensaje);
                        System.out.println(mensaje);
                        //Ventana2.mostrar.setText(mensaje);
                           
                    }
                }
                catch (SerialPortException ex)
                {Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);}
                
                catch (ArduinoException ex)
                {Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);}               
                
            }
        };*/
    // setSize (400,200);   
        
        initComponents();
        
   //     Ventana2 abrir = new Ventana2();
   //     abrir.setVisible(true);
        
       
        
        this.setSize(new Dimension(939, 634));
        this.setLocationRelativeTo(null);
        
    /*    try {
            arduino.arduinoRXTX("COM3", 9600, escucha);
        } catch (ArduinoException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
      */  
    }
//public static String compara = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserId = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        fondo_negro = new javax.swing.JLabel();
        jid_usuario_logooo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jbase = new javax.swing.JLabel();
        jregistro = new javax.swing.JLabel();
        jid_usuario = new javax.swing.JLabel();
        jmenu = new javax.swing.JLabel();
        jregistro_logo = new javax.swing.JLabel();
        jbase_logo = new javax.swing.JLabel();
        fondoGris_01 = new javax.swing.JLabel();
        bienvenida = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ipn = new javax.swing.JLabel();
        fondoGris_02 = new javax.swing.JLabel();
        ENTRAR = new javax.swing.JButton();
        admin = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        logo_candado = new javax.swing.JLabel();
        logo_usuario = new javax.swing.JLabel();
        fondoGris02 = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("home");
        setMaximumSize(new java.awt.Dimension(939, 634));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserId.setFont(new java.awt.Font("Cancun", 1, 24)); // NOI18N
        UserId.setForeground(new java.awt.Color(255, 255, 255));
        UserId.setText("IDENTIFICANDO USUARIO");
        getContentPane().add(UserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 570, -1, -1));

        usuario.setBackground(new java.awt.Color(255, 0, 0));
        usuario.setFont(new java.awt.Font("Cancun", 0, 24)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario:");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 600, 390, 26));

        fondo_negro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_negro.jpg"))); // NOI18N
        fondo_negro.setText("jLabel1");
        getContentPane().add(fondo_negro, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 550, 450, 90));

        jid_usuario_logooo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bici_logo02.png"))); // NOI18N
        jid_usuario_logooo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jid_usuario_logoooMouseClicked(evt);
            }
        });
        getContentPane().add(jid_usuario_logooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 390, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bici.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 260, -1, -1));

        jbase.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jbase.setText("Base de datos");
        getContentPane().add(jbase, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 330, -1, -1));

        jregistro.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jregistro.setText("Creditos de la App");
        getContentPane().add(jregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 470, -1, -1));

        jid_usuario.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jid_usuario.setText("Id. Usuario");
        getContentPane().add(jid_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 400, -1, -1));

        jmenu.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jmenu.setText("Menú");
        getContentPane().add(jmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 240, -1, -1));

        jregistro_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_creditos.png"))); // NOI18N
        jregistro_logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jregistro_logoMouseClicked(evt);
            }
        });
        getContentPane().add(jregistro_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 450, -1, -1));

        jbase_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro_logo.png"))); // NOI18N
        jbase_logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbase_logoMouseClicked(evt);
            }
        });
        getContentPane().add(jbase_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 320, -1, -1));

        fondoGris_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gris_10.jpg"))); // NOI18N
        fondoGris_01.setText("usua");
        getContentPane().add(fondoGris_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 230, 450, 320));

        bienvenida.setBackground(new java.awt.Color(255, 0, 0));
        bienvenida.setFont(new java.awt.Font("Cancun", 0, 48)); // NOI18N
        bienvenida.setForeground(new java.awt.Color(204, 0, 0));
        bienvenida.setText(" Poli-Bike");
        getContentPane().add(bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 300, 60));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 100, 50));

        ipn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ipn_logo.png"))); // NOI18N
        getContentPane().add(ipn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, -1, -1));

        fondoGris_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gris_09.png"))); // NOI18N
        fondoGris_02.setText("jLabel2");
        getContentPane().add(fondoGris_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 280, 70));

        ENTRAR.setFont(new java.awt.Font("Accent SF", 0, 18)); // NOI18N
        ENTRAR.setForeground(new java.awt.Color(0, 204, 204));
        ENTRAR.setText("ENTRAR");
        ENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTRARActionPerformed(evt);
            }
        });
        getContentPane().add(ENTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 150, 50));

        admin.setBackground(new java.awt.Color(0, 204, 204));
        admin.setFont(new java.awt.Font("DokChampa", 1, 18)); // NOI18N
        admin.setForeground(new java.awt.Color(0, 153, 153));
        admin.setText("Administrador:");
        getContentPane().add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 130, 30));

        pass.setBackground(new java.awt.Color(0, 204, 204));
        pass.setFont(new java.awt.Font("DokChampa", 1, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 153, 153));
        pass.setText("Password:");
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 100, 30));

        jTextField1.setText("USUARIO");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 210, 30));

        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 210, 30));

        logo_candado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/candado.png"))); // NOI18N
        getContentPane().add(logo_candado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        logo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Persona.png"))); // NOI18N
        getContentPane().add(logo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        fondoGris02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gris_10.jpg"))); // NOI18N
        fondoGris02.setText("jLabel1");
        getContentPane().add(fondoGris02, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 410, 200));

        wallpaper.setForeground(new java.awt.Color(255, 255, 255));
        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WALLPAPER.jpg"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTRARActionPerformed
        
            String Administrador = "Administrador1";
            String Password = "administradorONE";
            
            String Pass = new String(jPasswordField1.getPassword());
            
            if(Pass.equals(Password))
            {
                //JOptionPane.showMessageDialog(this, "Gracias por Acceder");
                           
                AnimationClass ELFONDO = new AnimationClass();  //FONDO GRIS  A CAMBIAR              
                AnimationClass EL_REGIS_LOGO = new AnimationClass();
                AnimationClass EL_USER_LOGO = new AnimationClass();
                AnimationClass EL_BASE_LOGO = new AnimationClass();
                
                AnimationClass EL_BASE = new AnimationClass();
                AnimationClass EL_USER = new AnimationClass();
                AnimationClass EL_REGIS = new AnimationClass();
                AnimationClass EL_MENU = new AnimationClass();
                
                
            /////////////////////--MOVIMIENTO--/////////////////////////    
                                 
                  ELFONDO.jLabelXLeft(990, 490, 20, 10, fondoGris_01); 
                  EL_REGIS_LOGO.jLabelXLeft(1090, 590, 20, 10, jregistro_logo);
                  EL_USER_LOGO.jLabelXLeft(1080, 580, 20, 10, jid_usuario_logooo);
                  EL_BASE_LOGO.jLabelXLeft(1090, 590, 20, 10, jbase_logo);  
                  
                  EL_BASE.jLabelXLeft(1190, 690, 20, 10, jbase);
                  EL_USER.jLabelXLeft(1200, 700, 20, 10, jid_usuario);
                  EL_REGIS.jLabelXLeft(1180, 680, 20, 10, jregistro);
                  EL_MENU.jLabelXLeft(1150, 650, 20, 10, jmenu);  
                  
            /////////////////////--MOVIMIENTO--/////////////////////////       
                  
            }
            else
            {JOptionPane.showMessageDialog(this, "ERROR, NO PUEDES ACCESAR");}

    }//GEN-LAST:event_ENTRARActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jid_usuario_logoooMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jid_usuario_logoooMouseClicked
    
    ////////////////////---Declaración de clases---/////////////////////////// 
       AnimationClass ELUSUARIO = new AnimationClass();
       AnimationClass ELIDENT = new AnimationClass();
       AnimationClass EL_FONDO_N = new AnimationClass();//FONDO NEGRO A CAMBIAR 
       
       AnimationClass EELUSUARIO = new AnimationClass();
       AnimationClass EELIDENT = new AnimationClass();
       AnimationClass EEL_FONDO_N = new AnimationClass();
    ////////////////////---Declaración de clases---/////////////////////////// 
       
       
    ////////////////////---Deslizar Izquierda---///////////////////////////   
        ELUSUARIO.jLabelXLeft(1020, 520, 20, 10, usuario);
                ELIDENT.jLabelXLeft(1050, 550, 20, 10, UserId);
                EL_FONDO_N.jLabelXLeft(990, 490, 20, 10, fondo_negro);
     ////////////////////---Deslizar Izquierda---///////////////////////////
                
    ////////////////////---Deslizar Derecha---///////////////////////////  
                EELUSUARIO.jLabelXRight(520, 1020, 20, 10, usuario);
                EELIDENT.jLabelXRight(550, 1050, 20, 10, UserId);
                EEL_FONDO_N.jLabelXRight(490, 990, 20, 10, fondo_negro);
    ////////////////////---Deslizar Derecha---///////////////////////////    
        
    }//GEN-LAST:event_jid_usuario_logoooMouseClicked

    private void jbase_logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbase_logoMouseClicked
   
        
        Ventana2 abrir = new Ventana2();
        abrir.setVisible(true);
        this.setVisible(false);
      //  this.setExtendedState(ICONIFIED);       //Minimizar
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jbase_logoMouseClicked

    private void jregistro_logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jregistro_logoMouseClicked
//Elefante Creditos
        
        Creditos abrir = new Creditos();
        abrir.setVisible(true);
      //  this.setVisible(false);
      //  this.setExtendedState(ICONIFIED);       //Minimizar
        
        



// TODO add your handling code here:
    }//GEN-LAST:event_jregistro_logoMouseClicked

    /**
     * @param args the command line arguments
     * 
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ENTRAR;
    private javax.swing.JLabel UserId;
    private javax.swing.JLabel admin;
    private javax.swing.JLabel bienvenida;
    private javax.swing.JLabel fondoGris02;
    private javax.swing.JLabel fondoGris_01;
    private javax.swing.JLabel fondoGris_02;
    private javax.swing.JLabel fondo_negro;
    private javax.swing.JLabel ipn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jbase;
    private javax.swing.JLabel jbase_logo;
    private javax.swing.JLabel jid_usuario;
    private javax.swing.JLabel jid_usuario_logooo;
    private javax.swing.JLabel jmenu;
    private javax.swing.JLabel jregistro;
    private javax.swing.JLabel jregistro_logo;
    private javax.swing.JLabel logo_candado;
    private javax.swing.JLabel logo_usuario;
    private javax.swing.JLabel pass;
    public static javax.swing.JLabel usuario;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
